STACK_WIDGET_TITLE = "SEC::Stack View"

TEXT_FONT = "Consolas"
TEXT_FONT_SIZE = 10
WIDGET_TITLE = "SEC:View"

STACK_SIZE_ABOVE = 20
STACK_SIZE_BELOW = 100

DEFINE_LINE_COLOR = "#000000"
TRANSPARENT = "#00FFFFFF"


DEFINE_BACKGROUND_COLOR = "#FFFFFF"
SELECT_LINE_BACKGROUND_COLOR = "#80AAAAAA"


# StackContainer:
DEBUG_BACKGROUND_COLOR =  "#CCFFFF"
QHEADER_BACKGROUND_COLOR = "#F3F3F3"
QHEADER_BACKGROUND_COLOR_HOVER = "#EDEDED"


# DataColor
STACK_ADDRESS_COLOR = "#0000FF"