STACK_WIDGET_TITLE = "SEC::Stack View"
WIDGET_TITLE = "Viewer"

TEXT_FONT = "Consolas"
TEXT_FONT_SIZE = 10


# loaded size
STACK_SIZE_ABOVE = 10
STACK_SIZE_BELOW = 60

STACK_SIZE_ABOVE_MAX = 20
STACK_SIZE_BELOW_MAX = 100

STACK_SIZE_ABOVE_MIN = 0
STACK_SIZE_BELOW_MIN = 40

ONCE_LOAD_SIZE = 3




DEFINE_LINE_COLOR = "#000000"
TRANSPARENT = "#00FFFFFF"


DEFINE_BACKGROUND_COLOR = "#FFFFFF"
SELECT_LINE_BACKGROUND_COLOR = "#80AAAAAA"


# StackContainer:
DEBUG_BACKGROUND_COLOR =  "#CCFFFF"

DEBUG_BACKGROUND_ROW_COLOR1 =  "#CCFFFF"
DEBUG_BACKGROUND_ROW_COLOR2 =  "#CCFBFF"

QHEADER_BACKGROUND_COLOR = "#F3F3F3"
QHEADER_BACKGROUND_COLOR_HOVER = "#EDEDED"

TEXT_SELECTED_COLOR = "#FFFFFF"
TEXT_SELECTED_BACKGROUND_COLOR = "#ADABA4"




# debug
STACK_POINTS_REGS_COLOR = "#ff6348"


# DataColor
STACK_ADDRESS_COLOR = "#808066"






# Data Type
T_VALUE = 0
T_CODE = 1
T_DATA = 2
T_STACK = 3
T_BSS = 4
T_CONST = 5


# description
MAX_DATA_DISPLAY_SIZE = 24
T_VALUE_SEG_COLOR = "#2980b9"
T_CODE_SEG_COLOR = "#ff7f50"
T_DATA_SEG_COLOR = "#ffa502"
T_STACK_SEG_COLOR = "#6c5ce7"
T_BSS_SEG_COLOR = "#b2bec3"
T_CONST_SEG_COLOR = "#747d8c"

T_CODE_COLOR = "#1700FF"
T_DATA_COLOR = "#1b1464"



ARROW_SYMBOL = ">>"
ARROW_SYMBOL_COLOR = "#636e72"



# remark
STACK_VARIBLE_REMARK_COLOR = "#8e44ad"
STACK_BASE_REMARK_COLOR = "#130f40"
STACK_RETURN_REMARK_COLOR = "#1e3799"



# variables container
DEBUG_BACKGROUND_LINE_COLOR1 =  "#CCFFFF"
DEBUG_BACKGROUND_LINE_COLOR2 =  "#CCFBFF"
SELECTED_ITEM_BACKGROUND_COLOR = "#8ed4fa"

TOP_ITEM_COLOR = "#2f3542"
FUNCTION_ITEM_COLOR = "#1b1464"

VAR_NAME_COLOR = "#8e44ad"
STKVAR_NAME_COLOR = "#8e44ad"
REGVAR_NAME_COLOR = "#5352ed"

VAR_TYPE_COLOR = "#00b894"
VAR_VALUE_COLOR = "#6c5ce7"
VAR_REMARK_COLOR = "#2f3542"
VAR_ADDR_COLOR = "#341f97"







